export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const FETCH_SKATESPOTS = "GET_SKATESPOTS";
export const CREATE_SKATESPOT = "CREATE_SKATESPOT";
export const FILTER_SKATESPOTS = "FILTER_SKATESPOTS";



